FROM ghcr.io/linuxserver/baseimage-ubuntu:arm32v7-focal

# set version label
ARG BUILD_DATE
ARG VERSION
ARG UNIFI_VERSION
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="aptalca"

# add local files
COPY root-armhf/ /
