#!/usr/bin/with-contenv bash

cd /config || exit

if [ -z ${MEM_LIMIT+x} ]; then
  MEM_LIMIT="1024M"
fi

if [ -z ${MEM_STARTUP+x} ]; then
    exec \
        s6-setuidgid abc java -Xmx"${MEM_LIMIT}" -jar /usr/lib/unifi/lib/ace.jar start;
else
    exec \
        s6-setuidgid abc java -Xms"${MEM_STARTUP}" -Xmx"${MEM_LIMIT}" -jar /usr/lib/unifi/lib/ace.jar start;
fi
