#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cat <<-EOF
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *     This Unifi-Controller image does not support     *
    *        32 bit ARM due to a lack of OS packages       *
    *                                                      *
    *                                                      *
    ********************************************************
    ********************************************************
EOF
