#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "┌─────────────────────────────────────────────────────────────────────────────┐"
echo "│                                                                             │"
echo "|                From 2024-01-01 this image will be deprecated                │"
echo "|                      and it will no longer be updated.                      │"
echo "│                                                                             │"
echo "│     See: https://info.linuxserver.io/issues/2023-09-06-unifi-controller     |"
echo "|                              for more details.                              │"
echo "│                                                                             │"
echo "├─────────────────────────────────────────────────────────────────────────────┤"
echo "│                                                                             │"
echo "│        Please migrate to our Unifi Network Application image instead:       │"
echo "│       https://github.com/linuxserver/docker-unifi-network-application       │"
echo "│                                                                             │"
echo "└─────────────────────────────────────────────────────────────────────────────┘"
