#!/usr/bin/with-contenv bash

if [[ "$(uname -m)" == "armv7l" ]]; then
    # We don't support armhf any more
    exit 0
fi

if [[ ! -d /usr/lib/unifi/bin ]]; then
    echo "*** installing unifi packages ***"
    export DEBIAN_FRONTEND=noninteractive
    dpkg -i /app/unifi.deb
fi