#!/usr/bin/with-contenv bash

if [[ "$(uname -m)" == "armv7l" ]]; then
cat <<-EOF
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *     This Unifi-Controller image does not support     *
    *   32 bit ARM due to lack of available OS packages    *
    *                                                      *
    *                                                      *
    ********************************************************
    ********************************************************
EOF
fi
