#!/usr/bin/with-contenv bash

# create our folders
mkdir -p \
	/config/{data,logs,run}


# create symlinks for config
symlinks=( \
/usr/lib/unifi/data \
/usr/lib/unifi/logs \
/usr/lib/unifi/run )

for i in "${symlinks[@]}"
do
[[ -L "$i" && ! "$i" -ef /config/"$(basename "$i")"  ]] && unlink "$i"
[[ ! -L "$i" ]] && ln -s /config/"$(basename "$i")" "$i"
done

if [[ ! -e /config/data/system.properties ]]; then
    cp /defaults/system.properties /config/data
fi

if [[ -n $MEM_LIMIT ]]; then
    echo "*** Setting Java memory limit to $MEM_LIMIT ***"
    echo "unifi.xmx=$MEM_LIMIT" >> /config/data/system.properties 
fi

if [[ -n $MEM_STARTUP ]]; then
    echo "*** Setting Java memory minimum to $MEM_STARTUP ***"
    echo "unifi.xms=$MEM_STARTUP" >> /config/data/system.properties
fi

# permissions
chown -R abc:abc \
	/config \
	/usr/lib/unifi
