#!/usr/bin/with-contenv bash

if [[ "$(uname -m)" == "armv7l" ]]; then
    # We don't support armhf any more
    exit 0
fi

# create our folders
mkdir -p \
    /config/{data,logs,run}


# create symlinks for config
symlinks=( \
/usr/lib/unifi/data \
/usr/lib/unifi/logs \
/usr/lib/unifi/run )

for i in "${symlinks[@]}"
do
[[ -L "$i" && ! "$i" -ef /config/"$(basename "$i")"  ]] && unlink "$i"
[[ ! -L "$i" ]] && ln -s /config/"$(basename "$i")" "$i"
done

if [[ ! -e /config/data/system.properties ]]; then
    cp /defaults/system.properties /config/data
    echo "Running remote? $MONGO_REMOTE"
    if [[ "$MONGO_REMOTE" = true ]]; then

        if [[ -z $DATABASE_HOST ]]; then
            echo "Missing DATABASE_HOST, this variable is required"
            exit 1
        fi

        if [[ -z $DATABASE_PORT ]]; then 
            $DATABASE_PORT = 27017
        fi

        echo "Using mongodb remote server $DATABASE_HOST:$DATABASE_PORT"
        COUNTER=0
        nc -zv $DATABASE_HOST $DATABASE_PORT
        while [[ $? -ne 0 && $COUNTER -lt 60 ]] ; do
    	    sleep 2
    	    let COUNTER+=2
    	    echo "Waiting for mongo to initialize... ($COUNTER seconds so far)"
    	    nc -zv $DATABASE_HOST $DATABASE_PORT
	    done
        
        if [[ $COUNTER -ne 60 ]]; then
           echo "Mongo connection worked"
           if [[ -z $DATABASE_NAME ]]; then
                echo "Missing database name"
                exit 1
           fi

           if [[ -z "$DATABASE_USER" ]]; then
               MONGO_URI=$( printf "mongodb://%s:%s/" $DATABASE_HOST $DATABASE_PORT )
           elif [[ "$DATABASE_USER" && "$DATABASE_PASS" && -z $AUTHENTICATION_DATABASE ]]; then
               MONGO_URI=$( printf "mongodb://%s:%s@%s:%s/" $DATABASE_USER $DATABASE_PASS $DATABASE_HOST $DATABASE_PORT )
           elif [[ "$DATABASE_USER" && "$DATABASE_PASS" && "$AUTHENTICATION_DATABASE" ]]; then
               MONGO_URI=$( printf "mongodb://%s:%s@%s:%s/%s?authSource=%s" $DATABASE_USER $DATABASE_PASS $DATABASE_HOST $DATABASE_PORT "%s" $AUTHENTICATION_DATABASE  )
           else
               echo "Not supported use case, check environments"
               exit 1
           fi

            #echo "$MONGO_URI"

            if [[ "$AUTHENTICATION_DATABASE" ]]; then
                printf "db.mongo.uri=$MONGO_URI\n" $DATABASE_NAME >> /config/data/system.properties
            else
                echo "db.mongo.uri=$MONGO_URI\n" >> /config/data/system.properties
            fi

            if [[ -z $STAT_DATABASE_NAME && "$AUTHENTICATION_DATABASE" ]]; then
                printf "statdb.mongo.uri=$MONGO_URI\n" "${DATABASE_NAME}_stat" >> /config/data/system.properties
            elif [[ "$STAT_DATABASE_NAME" && "$AUTHENTICATION_DATABASE" ]]; then
                printf "statdb.mongo.uri=$MONGO_URI\n" $STAT_DATABASE_NAME >> /config/data/system.properties
            elif [[ "$STAT_DATABASE_NAME" && -z $AUTHENTICATION_DATABASE ]]; then
                echo "statdb.mongo.uri=${MONGO_URI}${STAT_DATABASE_NAME}\n" >> /config/data/system.properties
            else
                echo "Skiping stat database property... unifi controller will try to handle it"
            fi

        else
           echo "Mongo connection failed"
           exit 1
        fi
        echo "db.mongo.local=false" >> /config/data/system.properties
        echo "unifi.db.name=$DATABASE_NAME" >> /config/data/system.properties

        # Tail for debugging propuses
        #tail -n 10 /config/data/system.properties
        
    elif [ ! -f /usr/bin/mongod ]; then
        echo "MongoDB Server not installed, use the full version image"
        exit 1
    fi
fi


if grep -q "xmx" /config/data/system.properties && grep -q "xms" /config/data/system.properties; then

    if [[ $MEM_LIMIT == "default" ]]; then
        echo "*** Setting Java memory limit to default ***"
        sed -i "/unifi.xmx=.*/d" /config/data/system.properties
    elif [[ -n $MEM_LIMIT ]]; then
        echo "*** Setting Java memory limit to $MEM_LIMIT ***"
        sed -i "s/unifi.xmx=.*/unifi.xmx=$MEM_LIMIT/" /config/data/system.properties 
    fi

    if [[ $MEM_STARTUP == "default" ]]; then
        echo "*** Setting Java memory minimum to default ***"
        sed -i "/unifi.xms=.*/d" /config/data/system.properties
    elif [[ -n $MEM_STARTUP ]]; then
        echo "*** Setting Java memory minimum to $MEM_STARTUP ***"
        sed -i "s/unifi.xms=.*/unifi.xms=$MEM_STARTUP/" /config/data/system.properties
    fi

elif grep -q "xmx" /config/data/system.properties; then

    if [[ $MEM_LIMIT == "default" ]]; then
        echo "*** Setting Java memory limit to default ***"
        sed -i "/unifi.xmx=.*/d" /config/data/system.properties
    elif [[ -n $MEM_LIMIT ]]; then
        echo "*** Setting Java memory limit to $MEM_LIMIT ***"
        sed -i "s/unifi.xmx=.*/unifi.xmx=$MEM_LIMIT/" /config/data/system.properties
    fi

    if [[ -n $MEM_STARTUP ]]; then
        echo "*** Setting Java memory minimum to $MEM_STARTUP ***"
        echo "unifi.xms=$MEM_STARTUP" >> /config/data/system.properties
    fi

elif grep -q "xms" /config/data/system.properties; then

    if [[ $MEM_STARTUP == "default" ]]; then
        echo "*** Setting Java memory minimum to default ***"
        sed -i "/unifi.xms=.*/d" /config/data/system.properties
    elif [[ -n $MEM_STARTUP ]]; then
        echo "*** Setting Java memory minimum to $MEM_STARTUP ***"
        sed -i "s/unifi.xms=.*/unifi.xms=$MEM_STARTUP/" /config/data/system.properties
    fi

    if [[ -n $MEM_LIMIT ]]; then
        echo "*** Setting Java memory limit to $MEM_LIMIT ***"
        echo "unifi.xmx=$MEM_LIMIT" >> /config/data/system.properties 
    fi

else

    if [[ -n $MEM_LIMIT ]]; then
        echo "*** Setting Java memory limit to $MEM_LIMIT ***"
        echo "unifi.xmx=$MEM_LIMIT" >> /config/data/system.properties 
    fi

    if [[ -n $MEM_STARTUP ]]; then
        echo "*** Setting Java memory minimum to $MEM_STARTUP ***"
        echo "unifi.xms=$MEM_STARTUP" >> /config/data/system.properties
    fi

fi

# permissions
chown -R abc:abc \
	/config \
	/usr/lib/unifi
